### ISSUE TITLE
Typo in https://draculatheme.com/idle

### ISSUE THREAD

**Issue by huoi** [dracula/idle#1]
When browsing the dracula theme website, I saw typos in the "Activating Theme" section as follow:

![image](https://user-images.githubusercontent.com/59074303/99162557-88fb8d80-2731-11eb-8097-9735bba30bfc.png)

Please fix this issue.

**Comment by zenorocha** [comment]
Can you take a look @timescam?

**Comment by rexkyng** [comment]
fixed it
